#!/bin/ksh
#*************************************************************************/
#* Script Name   : nih_transfer.sh			       	                 *
#* Creation Date : 03/22/2012                                            *
#* Created By    : Mariappan Muthiah                                     *
#*                                                                       *
#* Serial Number :                                                       * 
#*                                                                       *
#* Description   : Script to transfer NIH  file              	         *
#*                 						         *
#*                                                                       *
#* Input Parms:   File Name                                              *
#* Called By:     Manually;cron                                          *
#*                                                                       *
#*                                                                       *
#* Modifications:                                                        *
#* Who RMC  Date 08/11/2016  What Changed? Added robin.cunningham@hhs.gov*
#* -------- -------- --------------------------------------------------- *
#*************************************************************************/
p_mailid='lloyd.hamilton@psc.hhs.gov mariappan.muthiah@hhs.gov karen.williams@psc.hhs.gov marvin.simon@psc.hhs.gov robin.cunningham@hhs.gov minh.tran@hhs.gov'
FNAME="/data/BIISINT/data/int/out/LES/$1"
if [[ -n "$1" ]] ; then
if [ ! -e $FNAME ] 
then
echo "No such file at $FNAME exiting..." |mailx -s "Aborting:File $FNAME not found!" $p_mailid
exit
else
echo "Transfering file to m1csv301.hhs.gov (sa-nihbiisu account) on `date "+%m/%d/%Y"` at `date "+%T"` \t" |tee -a /tmp/nih.out
/usr/bin/sftp sa-cdirect@m1csv301.hhs.gov <<EOF
cd /opt/app/jail/sa-nihbiisu/outbound
put $FNAME
quit
EOF
echo "Transfer to m1csv301 (Dropbox) is now completed on `date "+%m/%d/%Y"` at `date "+%T"` \t" |tee -a /tmp/nih.out
echo "\n" |tee -a /tmp/nih.out
cat /tmp/nih.out|mailx -s "File $FNAME transfered to m1csv301 server sucessfully" $p_mailid
rm /tmp/nih.out
fi
else
echo "Usage :nih_transfer.sh <filename>"
exit                    
fi
